function <spm_MANTIS
% MANTIS Toolbox wrapper to call MANTIS functions
%_______________________________________________________________________
% Jian Chen

rev = '$Rev: 1 $';

SPMid = spm('FnBanner',mfilename,rev);
[Finter,Fgraph,CmdLine] = spm('FnUIsetup','MANTIS');
spm_help('!ContextHelp',mfilename);
spm_help('!Disp','MANTIS.man','',Fgraph,'   MANTIS toolbox for SPM8');

fig = spm_figure('GetWin','Interactive');
h0  = uimenu(fig,...
	'Label',	'MANTIS',...
	'Separator',	'on',...
	'Tag',		'MANTIS',...
	'HandleVisibility','on');
h1  = uimenu(h0,...
	'Label',	'SPM Segmentation run1 ',...
	'Separator',	'off',...
	'Tag',		'SPM Segmentation run1',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.mantis.segrun1'');',...
	'HandleVisibility','on');
h2  = uimenu(h0,...
	'Label',	'Adaptive CSF segmentation',...
	'Separator',	'off',...
	'Tag',		'Adaptive CSF segmentation',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.mantis.segcsf'');',...
 	'HandleVisibility','on');
h3  = uimenu(h0,...
	'Label',	'Clean White matter',...
	'Separator',	'off',...
	'Tag',		'Clean White matter',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.mantis.wmclean'');',...
 	'HandleVisibility','on');
h4  = uimenu(h0,...
	'Label',	'SPM Segmentation run2',...
	'Separator',	'off',...
	'Tag',		'SPM Segmentation run2',...
	'HandleVisibility','on');
h41  = uimenu(h4,...
	'Label',	'Make Custom Template',...
	'Separator',	'off',...
	'Tag',		'Make Custom Template',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.mantis.segrun2.maketemp'');',...
	'HandleVisibility','on');
h42  = uimenu(h4,...
	'Label',	'Segmentation run2',...
	'Separator',	'off',...
	'Tag',		'Segmentation run2',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.mantis.segrun2.seg2'');',...
	'HandleVisibility','on');
h5  = uimenu(h0,...
	'Label',	'Hard segmentation label',...
	'Separator',	'off',...
	'Tag',		'Hard segmentation label',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.mantis.hardlabel'');',...
	'HandleVisibility','on');
h6  = uimenu(h0,...
	'Label',	'Segmentation volumes',...
	'Separator',	'off',...
	'Tag',		'Segmentation volumes',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.mantis.calvol'');',...
	'HandleVisibility','on');
h7  = uimenu(h0,...
	'Label',	'Segmentation batch run',...
	'Separator',	'off',...
	'Tag',		'Segmentation batch run',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.mantis.batchrun'');',...
	'HandleVisibility','on');